
export const appTypes = {
  LOADING: 'LOADING',
}

export const userTypes = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  CLEAN_STATE: 'CLEAN_STATE'
}

export const cartTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
}

export const shopTypes = {
  SHOW_CATEGORY_SELECTED: 'SHOW_CATEGORY_SELECTED',
  GET_COLLECTIONS_FIREBASE: 'GET_COLLECTIONS_FIREBASE' 
}