export const userTypes = {

  USER_FETCHING: 'USER_FETCHING',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAIL',

  UPLOAD_USER_IMAGE_FAIL: 'UPLOAD_USER_IMAGE_FAIL',

  USER_LOGOUT: 'USER_LOGOUT',
}

export const cartTypes = {

  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',

  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',

  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
}

export const shopTypes = {

  GET_COLLECTION_FETCHING: 'GET_COLLECTION_FETCHING',
  GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS', 
  GET_COLLECTIONS_FAILURE: 'GET_COLLECTIONS_SUCCESS', 
  SHOW_COLLECTION_SELECTED: 'SHOW_COLLECTION_SELECTED'
  
}